NDefines.NGame.START_DATE = "1380.7.5"
NDefines.NGame.END_DATE = "1900.1.1"
NDefines.NDiplomacy.IMPERIAL_REFORM_COST = 75
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 4
NDefines.NCountry.PS_BUY_NATIVE_ADVANCEMENT = 800
NDefines.NGraphics.COLOR_WASTELANDS = 1